# Google App Engine configuration (Alternative to Cloud Run)
runtime: nodejs18

# Automatic scaling configuration
automatic_scaling:
  min_instances: 1
  max_instances: 50
  target_cpu_utilization: 0.6
  target_throughput_utilization: 0.6

# Resource allocation
resources:
  cpu: 2
  memory_gb: 4
  disk_size_gb: 10

# Environment variables
env_variables:
  NODE_ENV: production
  PORT: 8080

# Skip files during deployment
skip_files:
  - ^(.*/)?#.*#$
  - ^(.*/)?.*~$
  - ^(.*/)?.*\.py[co]$
  - ^(.*/)?.*/RCS/.*$
  - ^(.*/)?\..*$
  - ^(.*/)?node_modules/.*$
  - ^(.*/)?\.git.*$
  - ^(.*/)?\.vscode/.*$
  - ^(.*/)?\.replit$
  - ^(.*/)?replit\.nix$

# Health check configuration
readiness_check:
  path: "/health"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

liveness_check:
  path: "/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 4
  success_threshold: 2

# Network settings
network:
  session_affinity: false

# VPC access (if needed for Cloud SQL private IP)
vpc_access_connector:
  name: "projects/PROJECT_ID/locations/asia-south1/connectors/apmc-connector"