services:
  - type: web
    name: traderapp
    env: node
    plan: free
    buildCommand: ./build.sh
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: traderapp-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true

databases:
  - name: traderapp-db
    databaseName: traderapp
    user: traderapp