services:
  - type: web
    name: apmc-trader-app
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: apmc-database
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true

databases:
  - name: apmc-database
    databaseName: apmc_trader
    user: apmc_user
    plan: starter