services:
  - type: web
    name: apmc-trading-system
    env: node
    plan: starter
    region: oregon
    buildCommand: npm install && npm run db:push && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: PGHOST
        sync: false
      - key: PGDATABASE
        sync: false
      - key: PGUSER
        sync: false
      - key: PGPASSWORD
        sync: false
      - key: PGPORT
        value: 5432
      - key: SESSION_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
      - key: OPENAI_API_KEY
        sync: false
    scaling:
      minInstances: 1
      maxInstances: 3
    disk:
      name: apmc-disk
      size: 1GB
      mount: /var/data